// Generated by CoffeeScript 1.9.3
(function() {
  var AWS, AwsBus;

  AWS = require('aws-sdk');

  AwsBus = (function() {
    function AwsBus() {}

    AwsBus.prototype.configure = function(sqsUrl, snsArn, region, logger) {
      this.sqsUrl = sqsUrl;
      this.snsArn = snsArn;
      this.region = region;
      this.logger = logger;
      if (this.sqsUrl == null) {
        throw new Error("No SQS queue url provided");
      }
      if (this.snsArn == null) {
        throw new Error("No SNS topic arn provided");
      }
      if (this.region == null) {
        throw new Error("No region provided");
      }
      this.sqs = new AWS.SQS({
        region: this.region
      });
      return this.sns = new AWS.SNS({
        region: this.region
      });
    };

    AwsBus.prototype.send = function(message, done) {
      var sqsMessage;
      sqsMessage = {
        MessageBody: JSON.stringify(message),
        QueueUrl: this.sqsUrl
      };
      if (this.logger != null) {
        this.logger.debug("AwsBus: About to send to SQS");
      }
      return this.sqs.sendMessage(sqsMessage, (function(_this) {
        return function(err) {
          var snsMessage;
          if (err) {
            if (_this.logger != null) {
              _this.logger.error("AwsBus: SQS ERROR");
            }
            if (_this.logger != null) {
              _this.logger.error(err);
            }
            return done(err);
          }
          if (_this.logger != null) {
            _this.logger.debug("AwsBus: Sent to SQS");
          }
          snsMessage = {
            Message: 'Notification',
            TopicArn: _this.snsArn
          };
          if (_this.logger != null) {
            _this.logger.debug("AwsBus: About to publish to SNS");
          }
          return _this.sns.publish(snsMessage, function(err) {
            if (err) {
              if (_this.logger != null) {
                _this.logger.error("AwsBus: SNS ERROR");
              }
              if (_this.logger != null) {
                _this.logger.error(err);
              }
              return done(err);
            }
            if (_this.logger != null) {
              _this.logger.debug("AwsBus: Published to SNS");
            }
            return done(null);
          });
        };
      })(this));
    };

    return AwsBus;

  })();

  module.exports = new AwsBus();

}).call(this);

//# sourceMappingURL=index.js.map
